---
latitude: 42.34888
longitude: -71.08181
map_zoom: 12
name: Mandarin Oriental Boston
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 776 Boylston St
  street2: ''
  state: Massachusetts
  city: Boston
  country: United States
  zip_code: 02199
_hotel_id: MAN550
_portal_id: required-but-empty
_root_path: https://qa5.ttaws.com/rt
